MVC/ERP/HR/Models/Attendance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HR.Models
{
    public class Attendance
    {
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public DateTime AttendanceDate { get; set; }
        public bool IsPresent { get; set; }
    }
}

MVC/ERP/HR/Controllers/AttendanceController.cs
using HR.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HR.Controllers
{
    public class AttendanceController : Controller
    {
        // SHOW ALL
        public ActionResult Index()
        {
            AttendanceDAL dal = new AttendanceDAL();
            var list = dal.GetAllAttendance();
            return View(list);
        }

        // CREATE (GET)
        public ActionResult Create()
        {
            return View();
        }

        // CREATE (POST)
        [HttpPost]
        public ActionResult Create(Attendance obj)
        {
            if (ModelState.IsValid)
            {
                AttendanceDAL dal = new AttendanceDAL();
                dal.InsertAttendance(obj);
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // EDIT (GET)
        public ActionResult Edit(int id)
        {
            AttendanceDAL dal = new AttendanceDAL();
            var attendance = dal.GetAttendanceById(id);
            return View(attendance);
        }

        // EDIT (POST)
        [HttpPost]
        public ActionResult Edit(Attendance obj)
        {
            if (ModelState.IsValid)
            {
                AttendanceDAL dal = new AttendanceDAL();
                dal.UpdateAttendance(obj);
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        // DELETE (GET)
        public ActionResult Delete(int id)
        {
            AttendanceDAL dal = new AttendanceDAL();
            var attendance = dal.GetAttendanceById(id);
            return View(attendance);
        }

        // DELETE (POST)
        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            AttendanceDAL dal = new AttendanceDAL();
            dal.DeleteAttendance(id);
            return RedirectToAction("Index");
        }
    }
}

MVC/ERP/HR/Views/Attendance/Create.cshtml
@model HR.Models.Attendance

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AttendanceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttendanceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttendanceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPresent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPresent)
                    @Html.ValidationMessageFor(model => model.IsPresent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/ERP/HR/Views/Attendance/Delete.cshtml
@model HR.Models.Attendance

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Attendance</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AttendanceDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AttendanceDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPresent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPresent)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Attendance", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ID)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/ERP/HR/Views/Attendance/Edit.cshtml
@model HR.Models.Attendance

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Attendance</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AttendanceDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AttendanceDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AttendanceDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPresent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsPresent)
                    @Html.ValidationMessageFor(model => model.IsPresent, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MVC/ERP/HR/Views/Attendance/Index.cshtml
@model IEnumerable<HR.Models.Attendance>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AttendanceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPresent)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AttendanceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPresent)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>